import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        hairline: 'var(--color-hairline-border)',
        separator: 'var(--color-separator)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        tertiary: 'rgb(var(--color-tertiary) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--color-on-tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value>)',
        outline: 'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',
        scrim: 'rgb(var(--color-scrim) / <alpha-value>)',
        shadow: 'rgb(var(--color-shadow) / <alpha-value>)',
        error: 'rgb(var(--color-error) / <alpha-value>)',
        'on-error': 'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        'on-success': 'rgb(var(--color-on-success) / <alpha-value>)',
        'success-container': 'rgb(var(--color-success-container) / <alpha-value>)',
        'on-success-container': 'rgb(var(--color-on-success-container) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        'on-warning': 'rgb(var(--color-on-warning) / <alpha-value>)',
        'warning-container': 'rgb(var(--color-warning-container) / <alpha-value>)',
        'on-warning-container': 'rgb(var(--color-on-warning-container) / <alpha-value>)',
        info: 'rgb(var(--color-info) / <alpha-value>)',
        'on-info': 'rgb(var(--color-on-info) / <alpha-value>)',
        'info-container': 'rgb(var(--color-info-container) / <alpha-value>)',
        'on-info-container': 'rgb(var(--color-on-info-container) / <alpha-value>)',
        json: {
          key: '#7dd3fc',
          string: '#86efac',
          number: '#fbbf24',
          boolean: '#c4b5fd',
          punct: '#64748b',
        },
      },
      fontFamily: {
        brand: 'var(--font-family-brand)',
        plain: 'var(--font-family-plain)',
        sans: 'var(--font-family-plain)',
        display: 'var(--font-family-plain)',
        mono: 'var(--font-family-mono)',
      },
      boxShadow: {
        'elevation-0': 'var(--shadow-elevation-0)',
        'elevation-1': 'var(--shadow-elevation-1)',
        'elevation-2': 'var(--shadow-elevation-2)',
        'elevation-3': 'var(--shadow-elevation-3)',
        'elevation-4': 'var(--shadow-elevation-4)',
        'elevation-5': 'var(--shadow-elevation-5)',
        'soft-sm': 'var(--shadow-soft-sm)',
        'soft-md': 'var(--shadow-soft-md)',
        'soft-lg': 'var(--shadow-soft-lg)',
        'card-rest': 'var(--shadow-card-rest)',
        'card-hover': 'var(--shadow-card-hover)',
        'focus-ring': 'var(--shadow-focus-ring)',
      },
      borderRadius: {
        card: 'var(--radius-card)',
        'card-lg': 'var(--radius-card-lg)',
        button: 'var(--radius-button)',
        input: 'var(--radius-input)',
        badge: 'var(--radius-badge)',
        compact: 'var(--radius-compact)',
      },
      zIndex: {
        deep: 'var(--z-deep)',
        base: 'var(--z-base)',
        raised: 'var(--z-raised)',
        sticky: 'var(--z-sticky)',
        fixed: 'var(--z-fixed)',
        drawer: 'var(--z-drawer)',
        dropdown: 'var(--z-dropdown)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        tooltip: 'var(--z-tooltip)',
        notification: 'var(--z-notification)',
        overlay: 'var(--z-overlay)',
        max: 'var(--z-max)',
      },
      transitionDuration: {
        'short-1': 'var(--duration-short1)',
        'short-2': 'var(--duration-short2)',
        'short-3': 'var(--duration-short3)',
        'short-4': 'var(--duration-short4)',
        'medium-1': 'var(--duration-medium1)',
        'medium-2': 'var(--duration-medium2)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
      },
      transitionTimingFunction: {
        standard: 'var(--easing-standard)',
        'standard-decelerate': 'var(--easing-standard-decelerate)',
        'standard-accelerate': 'var(--easing-standard-accelerate)',
        emphasized: 'var(--easing-emphasized)',
        'emphasized-decelerate': 'var(--easing-emphasized-decelerate)',
        'emphasized-accelerate': 'var(--easing-emphasized-accelerate)',
      },
      opacity: {
        'state-hover': 'var(--state-hover-opacity)',
        'state-focus': 'var(--state-focus-opacity)',
        'state-pressed': 'var(--state-pressed-opacity)',
      },
      screens: {
        '3xl': '1920px',
        '4xl': '2560px',
        '5xl': '3840px',
      },
      keyframes: {
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          '0%': { opacity: '0', transform: 'translateY(-16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        shimmer: { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        skeleton: { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.4' } },
        'ping-soft': { '75%, 100%': { transform: 'scale(1.8)', opacity: '0' } },
      },
      animation: {
        'fade-in': 'fade-in 150ms var(--easing-standard) both',
        'fade-in-up': 'fade-in-up 300ms var(--easing-emphasized-decelerate) both',
        'fade-up': 'fade-in-up 300ms var(--easing-emphasized-decelerate) both',
        'fade-in-down': 'fade-in-down 150ms var(--easing-standard-decelerate) both',
        'scale-in': 'scale-in 150ms var(--easing-standard) both',
        shimmer: 'shimmer 2.4s linear infinite',
        skeleton: 'skeleton 1.6s ease-in-out infinite',
        'ping-soft': 'ping-soft 1.8s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
    },
  },
  plugins: [],
} satisfies Config;
